# Site settings
title: SMCCoder's Blog
email: sofie.christie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  SMCCoder is a Senior at the Academy of Arts and Adademics who
  loves to explore computer science as a self-learner and has
  studied multiple languages, including Java, Python, and Javascript.
  Her favorite library is D3.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://smccoder.github.io" # the base hostname & protocol for your site
github_username:  SMCCoder
#excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
